name: MCServer
image: ubuntu-14-04-x64
config:
  #cloud-config
  packages:
    - git
  runcmd:
    - cd /tmp && git clone https://github.com/cuberite/mcserver-ocean.git
    - cd /tmp/mcserver-ocean && ./initialinstall.sh
